"""
Django conf for spambot project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/conf/

For the full list of conf and their values, see
https://docs.djangoproject.com/en/1.10/ref/conf/
"""

from split_settings.tools import optional, include


include(
    "conf/core.py",
    "conf/installed_apps.py",
    "conf/middleware.py",
    "conf/urls.py",
    "conf/templates.py",
    "conf/databases.py",
    "conf/auth.py",
    "conf/i18n.py",
    "conf/core.py",
    "conf/api.py",
    optional("local_settings.py"),
)
