# Generated by Django 2.1.3 on 2018-11-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("crm", "0025_auto_20181120_0846")]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=20)),
                ("comment", models.TextField()),
                ("state_modified", models.DateTimeField()),
                ("notify_after", models.DateTimeField()),
            ],
            options={"verbose_name_plural": "Activities"},
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(null=True)),
                ("end", models.DateField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("template", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CampaignAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.FileField(null=True, upload_to="")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_attachments",
                        to="campaign.Campaign",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_activity",
                to="campaign.Campaign",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_activities",
                to="crm.Contact",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="opportunity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_activity",
                to="crm.Opportunity",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="other_contacts",
            field=models.ManyToManyField(
                blank=True, related_name="other_contact_activities", to="crm.Contact"
            ),
        ),
    ]
