# Generated by Django 2.1.3 on 2018-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="campaign", name="name", field=models.CharField(max_length=255)
        ),
    ]
