# Generated by Django 2.1.3 on 2018-11-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0003_campaignpredicate")]

    operations = [
        migrations.AddField(
            model_name="campaignpredicate",
            name="predicate",
            field=models.CharField(
                choices=[
                    ("contact.state", "Contact state"),
                    ("role.location.region", "Region"),
                    ("role.location.region", "Country"),
                    ("role.skills.name", "Skill"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaignpredicate",
            name="predicate_value",
            field=models.TextField(null=True),
        ),
    ]
