# Generated by Django 2.1.3 on 2018-11-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0004_auto_20181120_1027")]

    operations = [
        migrations.RenameField(
            model_name="campaignpredicate",
            old_name="predicate",
            new_name="predicate_field",
        ),
        migrations.AddField(
            model_name="campaignpredicate",
            name="inverse",
            field=models.BooleanField(default=False),
        ),
    ]
