# Generated by Django 2.1.3 on 2018-11-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0005_auto_20181120_1041")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("awaiting", "Awaiting"),
                    ("progress", "In Progress"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="new",
                max_length=20,
            ),
        )
    ]
