# Generated by Django 2.1.3 on 2018-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0007_auto_20181120_1232")]

    operations = [
        migrations.AlterField(
            model_name="campaignpredicate",
            name="predicate_field",
            field=models.CharField(
                choices=[
                    ("contact__state", "Contact state"),
                    ("role__location__region", "Region"),
                    ("role__location__country", "Country"),
                    ("role__skills.name", "Skill"),
                ],
                max_length=255,
                null=True,
            ),
        )
    ]
