# Generated by Django 2.1.3 on 2018-11-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0008_auto_20181120_1237")]

    operations = [
        migrations.AlterField(
            model_name="campaignpredicate",
            name="predicate_field",
            field=models.CharField(
                choices=[
                    ("contact__state", "Contact state"),
                    ("contact_role", "Contact Type"),
                    ("role__location__region", "Region"),
                    ("role__location__country", "Country"),
                    ("role__skills__name", "Skill"),
                ],
                max_length=255,
                null=True,
            ),
        )
    ]
