# Generated by Django 2.1.3 on 2018-11-20 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("campaign", "0009_auto_20181120_1245")]

    operations = [
        migrations.RemoveField(model_name="activity", name="state_modified"),
        migrations.AddField(
            model_name="activity",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
