# Generated by Django 2.1.3 on 2018-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0010_auto_20181120_1256")]

    operations = [
        migrations.AlterField(
            model_name="activity", name="comment", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="activity",
            name="notify_after",
            field=models.DateTimeField(null=True),
        ),
    ]
