# Generated by Django 2.1.3 on 2018-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0012_activity_role")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="subject",
            field=models.CharField(max_length=255, null=True),
        )
    ]
