# Generated by Django 2.1.3 on 2018-11-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0014_auto_20181123_1343")]

    operations = [
        migrations.AddField(
            model_name="campaignpredicate",
            name="predicate_condition",
            field=models.CharField(
                choices=[
                    ("__icontains", "Contains"),
                    ("__exact", "Is"),
                    ("__istartswith", "Starts with"),
                    ("__iendswith", "Ends with"),
                ],
                default="__icontains",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="campaignpredicate",
            name="predicate_field",
            field=models.CharField(
                choices=[
                    ("contact__state", "Contact state"),
                    ("contact_role", "Contact Type"),
                    ("role__location__region", "Region"),
                    ("role__location__country", "Country"),
                    ("role__location__location", "Location"),
                    ("role__primary_skill__name", "Primary Skill"),
                    ("role__secondary_skills", "Secondary Skills"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
