# Generated by Django 2.1.3 on 2018-11-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0015_auto_20181125_1949")]

    operations = [
        migrations.AlterField(
            model_name="campaignpredicate",
            name="predicate_field",
            field=models.CharField(
                choices=[
                    ("contact__state", "Contact state"),
                    ("contact_role", "Contact Type"),
                    ("contact__email", "Contact's Email"),
                    ("contact__first_name", "Contact's First Name"),
                    ("contact__last_name", "Contact's Last Name"),
                    ("role__name", "Role Name"),
                    ("role__requirements", "Requirements"),
                    ("role__state", "Status"),
                    ("role__from_level__title", "From Level"),
                    ("role__to_level__title", "To Level"),
                    ("role__import_key", "Role ID"),
                    ("role__primary_skill__name", "Primary Skill"),
                    ("role__secondary_skills", "Secondary Skills"),
                    ("role__location__region", "Region"),
                    ("role__location__country", "Country"),
                    ("role__location__location", "Location"),
                    ("opportunity__opportunity_name", "Opportunity"),
                ],
                max_length=255,
                null=True,
            ),
        )
    ]
