# Generated by Django 2.1.3 on 2018-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0016_auto_20181125_2010")]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
