# Generated by Django 2.1.3 on 2018-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_auto_20181125_1949"),
        ("campaign", "0017_auto_20181125_2055"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="opportunities",
            field=models.ManyToManyField(
                default=None,
                related_name="opportunity_activities",
                to="crm.Opportunity",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="role_activities_list", to="crm.Role"
            ),
        ),
    ]
