# Generated by Django 2.1.3 on 2018-11-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0018_auto_20181127_1554")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="opportunities",
            field=models.ManyToManyField(
                related_name="opportunity_activities", to="crm.Opportunity"
            ),
        )
    ]
