# Generated by Django 2.1.3 on 2018-11-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("campaign", "0019_auto_20181127_1558")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_activity",
                to="crm.Opportunity",
            ),
        )
    ]
