# Generated by Django 2.1.3 on 2018-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0020_auto_20181127_1559")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="aggregate_activities",
            field=models.BooleanField(
                default=True, verbose_name="Do not create duplicates"
            ),
        )
    ]
