# Generated by Django 2.1.3 on 2018-11-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_auto_20181125_1949"),
        ("campaign", "0022_auto_20181127_1812"),
    ]

    operations = [
        migrations.RemoveField(model_name="activity", name="opportunity"),
        migrations.RemoveField(model_name="activity", name="role"),
        migrations.AddField(
            model_name="activity",
            name="opportunity_contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="opportunity_contact_activities",
                to="crm.OpportunityContact",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="wave",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wave_activities",
                to="campaign.Wave",
            ),
        ),
    ]
