# Generated by Django 2.1.3 on 2018-11-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_auto_20181125_1949"),
        ("campaign", "0023_auto_20181128_0725"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityOpportunityContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.RemoveField(model_name="activity", name="opportunity_contacts"),
        migrations.AddField(
            model_name="activityopportunitycontact",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_opportunity_contacts",
                to="campaign.Activity",
            ),
        ),
        migrations.AddField(
            model_name="activityopportunitycontact",
            name="opportunty_contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_contact_activities",
                to="crm.OpportunityContact",
            ),
        ),
    ]
