# Generated by Django 2.1.3 on 2018-11-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_auto_20181125_1949"),
        ("campaign", "0025_auto_20181128_0809"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityopportunitycontact",
            name="opportunity",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_activity_contacts",
                to="crm.Opportunity",
            ),
        ),
        migrations.AddField(
            model_name="activityopportunitycontact",
            name="role",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_activity_contacts",
                to="crm.Role",
            ),
        ),
    ]
