# Generated by Django 2.1.3 on 2018-11-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0026_auto_20181128_0817")]

    operations = [
        migrations.RemoveField(model_name="activity", name="opportunities"),
        migrations.RemoveField(model_name="activity", name="roles"),
        migrations.AddField(
            model_name="activityopportunitycontact",
            name="contact_role",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
