# Generated by Django 2.1.3 on 2018-11-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("campaign", "0027_auto_20181128_0819")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="html_template",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="activityopportunitycontact",
            name="opportunity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_activity_contacts",
                to="crm.Opportunity",
            ),
        ),
        migrations.AlterField(
            model_name="activityopportunitycontact",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_activity_contacts",
                to="crm.Role",
            ),
        ),
    ]
