# Generated by Django 2.1.3 on 2018-11-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaign", "0028_auto_20181128_1308")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="html_body",
            field=models.TextField(blank=True, null=True),
        )
    ]
