# Generated by Django 2.1.3 on 2019-01-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("campaign", "0029_activity_html_body")]

    operations = [
        migrations.CreateModel(
            name="CampaignProperty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.TextField(null=True)),
                ("comment", models.TextField(null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_properties",
                        to="campaign.Campaign",
                    ),
                ),
            ],
        )
    ]
