# Generated by Django 2.1.3 on 2019-01-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("campaign", "0030_campaignproperty")]

    operations = [
        migrations.CreateModel(
            name="CampaignPostAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "field",
                    models.CharField(
                        choices=[("contact__state", "Contact state")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("value", models.TextField(null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_post_actions",
                        to="campaign.Campaign",
                    ),
                ),
            ],
        )
    ]
