# Generated by Django 2.1.3 on 2019-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_auto_20181125_1949"),
        ("campaign", "0031_campaignpostaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignpredicate",
            options={"verbose_name": "Trigger", "verbose_name_plural": "Triggers"},
        ),
        migrations.AlterModelOptions(
            name="campaignproperty",
            options={
                "verbose_name": "Template property",
                "verbose_name_plural": "Template properties",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="cc",
            field=models.ManyToManyField(
                blank=True, related_name="campaign_cc_contacts", to="crm.Contact"
            ),
        ),
    ]
