# Generated by Django 2.1.7 on 2020-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_contact_display_name'),
        ('campaign', '0032_auto_20190219_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bcc',
            field=models.ManyToManyField(blank=True, related_name='campaign_bcc_contacts', to='crm.Contact'),
        ),
    ]
