# Generated by Django 2.1.7 on 2020-05-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0033_campaign_bcc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='bcc',
        ),
    ]
