repos:
  - repo: local
    hooks:
      -   id: black
          entry: black
          name: Black Codestyle Formatter
          language: system
          types: [python]
      -   id: pylint
          name: Check Code Style Compliance
          entry: pylint --rcfile=.pylintrc --ignore-patterns=.*.py
          language: system
          types: [python]
          verbose: true
          pass_filenames: true
#      -   id: mdm-unittest
#          name: Unit Testing
#          entry: pytest --cov-append
#          always_run: true
#          language: system
#          verbose: true
#          pass_filenames: false
          # types: [python]
#      -   id: mdm-coverage
#          name: Test Coverage
#          entry: pytest --cov=api,crm tests/
#          always_run: true
#          language: system
#          verbose: true
#          pass_filenames: false
          # types: [python]
  