# Generated by Django 2.1.3 on 2018-11-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("comment", models.CharField(max_length=200)),
                ("stateModified", models.DateTimeField()),
                ("notifyAfter", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("created", models.DateTimeField()),
                ("name", models.CharField(max_length=100)),
                ("template", models.CharField(max_length=100)),
                ("attachments", models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_activities",
                to="crm.Campaign",
            ),
        ),
    ]
