# Generated by Django 2.1.3 on 2018-11-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CampaignAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachments", models.FileField(upload_to="")),
            ],
        ),
        migrations.RemoveField(model_name="campaign", name="attachments"),
        migrations.AlterField(
            model_name="campaign",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="campaign", name="end", field=models.DateField(null=True)
        ),
        migrations.AlterField(
            model_name="campaign", name="start", field=models.DateField(null=True)
        ),
        migrations.AlterField(
            model_name="campaign", name="template", field=models.TextField()
        ),
        migrations.AddField(
            model_name="campaignattachment",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_attachments",
                to="crm.Campaign",
            ),
        ),
    ]
