# Generated by Django 2.1.3 on 2018-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0002_auto_20181108_1059")]

    operations = [
        migrations.AlterField(
            model_name="activity", name="comment", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="activity", name="state", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="campaign", name="name", field=models.TextField()
        ),
    ]
