# Generated by Django 2.1.3 on 2018-11-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_account_contact_opportunity_opportunitycontact"),
        ("crm", "0004_level_location_role_skill"),
    ]

    operations = []
