# Generated by Django 2.1.3 on 2018-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0005_merge_20181109_0947")]

    operations = [
        migrations.AddField(
            model_name="role",
            name="from_level",
            field=models.ManyToManyField(
                blank=True, related_name="from_level", to="crm.Level"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="to_level",
            field=models.ManyToManyField(
                blank=True, related_name="to_level", to="crm.Level"
            ),
        ),
    ]
