# Generated by Django 2.1.3 on 2018-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0006_auto_20181109_1425")]

    operations = [
        migrations.RemoveField(model_name="role", name="from_level"),
        migrations.RemoveField(model_name="role", name="to_level"),
        migrations.AddField(
            model_name="level",
            name="from_level",
            field=models.ManyToManyField(
                blank=True, related_name="from_level", to="crm.Role"
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="to_level",
            field=models.ManyToManyField(
                blank=True, related_name="to_level", to="crm.Role"
            ),
        ),
    ]
