# Generated by Django 2.1.3 on 2018-11-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0007_auto_20181109_1438")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="contact_accounts", to="crm.Contact"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="opportunities",
            field=models.ManyToManyField(
                blank=True, related_name="opportunity_accounts", to="crm.Opportunity"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="contact",
            field=models.ManyToManyField(
                related_name="contact_activities", to="crm.Contact"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="opportunity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_activities",
                to="crm.Opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_roles",
                to="crm.Role",
            ),
        ),
    ]
