# Generated by Django 2.1.3 on 2018-11-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crm", "0008_auto_20181109_1456")]

    operations = [
        migrations.RenameField(
            model_name="skill", old_name="skillrole", new_name="role_skills"
        )
    ]
