# Generated by Django 2.1.3 on 2018-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0009_auto_20181109_1505")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="contact",
            field=models.ManyToManyField(
                blank=True, related_name="contact_activities", to="crm.Contact"
            ),
        )
    ]
