# Generated by Django 2.1.3 on 2018-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0010_auto_20181109_1518")]

    operations = [
        migrations.AlterField(
            model_name="campaignattachment",
            name="attachments",
            field=models.FileField(upload_to="attachment"),
        )
    ]
