# Generated by Django 2.1.3 on 2018-11-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0011_auto_20181109_1748")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="opportunities",
            field=models.ManyToManyField(
                blank=True, related_name="opportunity_accounts", to="crm.Opportunity"
            ),
        )
    ]
