# Generated by Django 2.1.3 on 2018-11-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crm", "0012_auto_20181113_0753")]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="name", new_name="account_name"
        ),
        migrations.RenameField(
            model_name="contact", old_name="role", new_name="contact_role"
        ),
        migrations.RenameField(
            model_name="contact", old_name="state", new_name="contact_state"
        ),
        migrations.RenameField(
            model_name="opportunity", old_name="name", new_name="opportunity_name"
        ),
    ]
