# Generated by Django 2.1.3 on 2018-11-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crm", "0013_auto_20181114_0755")]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="email", new_name="contact_email"
        )
    ]
