# Generated by Django 2.1.3 on 2018-11-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crm", "0015_auto_20181116_0853")]

    operations = [
        migrations.RenameField(
            model_name="opportunitycontact", old_name="contacts", new_name="contact"
        ),
        migrations.RenameField(
            model_name="opportunitycontact",
            old_name="opportunities",
            new_name="opportunity",
        ),
    ]
