# Generated by Django 2.1.3 on 2018-11-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0016_auto_20181116_1402")]

    operations = [
        migrations.RenameField(
            model_name="activity", old_name="notifyAfter", new_name="notify_after"
        ),
        migrations.RenameField(
            model_name="activity", old_name="stateModified", new_name="state_modified"
        ),
        migrations.RenameField(
            model_name="contact", old_name="contact_role", new_name="role"
        ),
        migrations.RemoveField(model_name="campaignattachment", name="attachments"),
        migrations.RemoveField(model_name="contact", name="contact_email"),
        migrations.RemoveField(model_name="opportunity", name="role"),
        migrations.AddField(
            model_name="campaignattachment",
            name="attachment",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="role",
            name="opportunity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_roles",
                to="crm.Opportunity",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign_activity",
                to="crm.Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="opportunity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_activity",
                to="crm.Opportunity",
            ),
        ),
        migrations.AlterField(
            model_name="activity", name="state", field=models.CharField(max_length=20)
        ),
        migrations.AlterField(
            model_name="opportunitycontact",
            name="project_role",
            field=models.CharField(
                choices=[("primary", "primary"), ("key_contact", "key_contact")],
                default="primary",
                max_length=20,
            ),
        ),
    ]
