# Generated by Django 2.1.3 on 2018-11-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crm", "0017_auto_20181116_1853")]

    operations = [
        migrations.RenameField(
            model_name="opportunitycontact", old_name="project_role", new_name="role"
        )
    ]
