# Generated by Django 2.1.3 on 2018-11-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0018_auto_20181116_1903")]

    operations = [
        migrations.RemoveField(model_name="level", name="from_level"),
        migrations.RemoveField(model_name="level", name="to_level"),
        migrations.AddField(
            model_name="role",
            name="from_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles_from_level",
                to="crm.Level",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="to_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles_to_level",
                to="crm.Role",
            ),
        ),
        migrations.AlterField(
            model_name="level", name="number", field=models.CharField(max_length=128)
        ),
        migrations.AlterField(
            model_name="role",
            name="opportunity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunity_roles",
                to="crm.Opportunity",
            ),
        ),
    ]
