# Generated by Django 2.1.3 on 2018-11-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0019_auto_20181116_2216")]

    operations = [
        migrations.AddField(
            model_name="role",
            name="import_key",
            field=models.CharField(max_length=64, null=True),
        )
    ]
