# Generated by Django 2.1.3 on 2018-11-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("crm", "0020_role_import_key")]

    operations = [
        migrations.RenameField(model_name="role", old_name="role", new_name="name")
    ]
