# Generated by Django 2.1.3 on 2018-11-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0022_auto_20181116_2248")]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("active", "active"),
                    ("inactive", "inactive"),
                ],
                default="new",
                max_length=30,
            ),
        )
    ]
