# Generated by Django 2.1.3 on 2018-11-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0024_auto_20181116_2257")]

    operations = [
        migrations.AlterModelOptions(
            name="opportunity", options={"verbose_name_plural": "Opportunities"}
        ),
        migrations.AlterField(
            model_name="opportunitycontact",
            name="role",
            field=models.CharField(
                choices=[
                    ("primary", "Primary Contect"),
                    ("key_contact", "Key contact"),
                ],
                default="primary",
                max_length=20,
            ),
        ),
    ]
