# Generated by Django 2.1.3 on 2018-11-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0025_auto_20181120_0846")]

    operations = [
        migrations.AddField(
            model_name="opportunitycontact",
            name="contact_role",
            field=models.CharField(
                choices=[
                    ("primary", "Primary Contact"),
                    ("key_contact", "Key contact"),
                ],
                default="primary",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="opportunitycontact",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_contacts",
                to="crm.Role",
            ),
        ),
    ]
