# Generated by Django 2.1.3 on 2018-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0026_auto_20181120_1232")]

    operations = [
        migrations.RemoveField(model_name="skill", name="role_skills"),
        migrations.AddField(
            model_name="role",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="skill_roles", to="crm.Skill"
            ),
        ),
    ]
