# Generated by Django 2.1.3 on 2018-11-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0025_auto_20181120_1034"),
        ("crm", "0027_auto_20181120_1237"),
    ]

    operations = []
