# Generated by Django 2.1.3 on 2018-11-21 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0028_merge_20181121_1029")]

    operations = [
        migrations.AlterField(
            model_name="opportunitycontact",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_contacts",
                to="crm.Role",
            ),
        )
    ]
