# Generated by Django 2.1.3 on 2018-11-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0029_auto_20181121_1229")]

    operations = [
        migrations.RemoveField(model_name="role", name="skills"),
        migrations.AddField(
            model_name="role",
            name="primary_skill",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_roles",
                null=True,
                to="crm.Skill",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="secondary_skills",
            field=models.TextField(default=None, null=True),
        ),
    ]
