# Generated by Django 2.1.3 on 2018-11-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("crm", "0031_auto_20181123_1036")]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="primary_skill",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_roles",
                to="crm.Skill",
            ),
        )
    ]
