# Generated by Django 2.1.3 on 2019-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_auto_20181125_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='valid_from',
            field=models.DateTimeField(null=True, verbose_name='date valid from'),
        ),
        migrations.AlterField(
            model_name='role',
            name='valid_till',
            field=models.DateTimeField(null=True, verbose_name='date valid till'),
        ),
    ]
