# Generated by Django 2.1.3 on 2019-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_auto_20190309_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
