# Generated by Django 2.1.3 on 2019-03-09 09:18

from django.db import migrations, models
from django.db.models import F

from crm.models.contact import Contact


def migration(*args, **kwargs):
    for c in Contact.objects.all():
        c.display_name = " ".join(map(lambda w: w.capitalize(), c.full_name.split(" ")))
        c.save()


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0034_contact_display_name'),
    ]

    operations = [
        migrations.RunPython(migration),
    ]
