# Generated by Django 2.1.3 on 2018-11-20 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("etl", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="etltask", name="log", field=models.TextField(null=True)
        ),
        migrations.AlterField(
            model_name="etltask",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
