# Generated by Django 2.1.3 on 2018-11-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0003_auto_20181120_0846"),
        ("etl", "0003_auto_20181120_1034"),
    ]

    operations = []
